apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Integration & Delivery
    containerImage: quay.io/hyperfoil/horreum-operator:0.7.9
    description: Performance results repository
    repository: https://github.com/hyperfoil/horreum-operator
    support: Red Hat Application Runtimes Performance Team
  name: horreum-operator.0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Horreum is the object configuring Horreum performance results repository
      displayName: Horreum
      kind: Horreum
      name: horreums.hyperfoil.io
      version: v1alpha1
  description: Performance results repository
  displayName: Horreum
  icon:
  - base64data: |
      iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAABhGlDQ1BJQ0MgcHJvZmlsZQAAKJF9
      kT1Iw0AcxV/TSkVaHAwi4pChOlkQFREnrUIRKoRaoVUH89EvaNKQpLg4Cq4FBz8Wqw4uzro6uAqC
      4AeIm5uToouU+L+k0CLGg+N+vLv3uHsHcI2KolmhMUDTbTOdTAjZ3KoQfkUI/YhiBrykWMacKKbg
      O77uEWDrXZxl+Z/7c0TVvKUAAYF4VjFMm3iDeGrTNhjvE/NKSVKJz4lHTbog8SPTZY/fGBdd5lgm
      b2bS88Q8sVDsYLmDlZKpEU8Sx1RNp3wu67HKeIuxVqkprXuyF0by+soy02kOIYlFLEGEABk1lFGB
      jTitOikW0rSf8PEPun6RXDK5ylDIsYAqNEiuH+wPfndrFSbGvaRIAuh6cZyPYSC8CzTrjvN97DjN
      EyD4DFzpbX+1AUx/kl5va7EjoHcbuLhua/IecLkDDDwZkim5UpAmVygA72f0TTmg7xboWfN6a+3j
      9AHIUFepG+DgEBgpUva6z7u7O3v790yrvx+RE3KzUJ2xwQAAAAZiS0dEAP8A0QAAv2wj9AAAAAlw
      SFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+UEFg4KE35gCkwAAAAZdEVYdENvbW1lbnQAQ3JlYXRl
      ZCB3aXRoIEdJTVBXgQ4XAAABSUlEQVR42u3bsQ2CQBSAYThchNKEEE1cw4Jd1BloHIaELYwJCY2d
      LHLgBNoZIHxf+5rLy3/XXZIA25X+Gh5vzWmaksesJ8zGvKurYY3LLS9tEdLYz7u+sH/ez69v8+AO
      bJsABIAAEAACQAAIAAEgAASAABAAAkAACAABIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgAASA
      ABAAAkAACAABIAAEgAAQAAJAAMxlt/gTxvA+XJuVrjd6ARAAAkAACAABIAAEgAAQAAJAAAgAASAA
      BIAAEAACQAAIAAEgAP5p+f8CsjHv6mpY43LLS1uENPZeAASAABAAAkAACAABIAAEgAAQAAJAAAgA
      ASAABIAAEAACQAAIAAEgAASAABAAAkAACAABIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgAASA
      ABAAbNwHrgkbLzobYhAAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - performance
  - repository
  - database
  - results
  - hyperfoil
  - benchmark
  links:
  - name: Horreum Operator
    url: https://horreum-operator.domain
  maintainers:
  - email: rvansa@redhat.com
    name: Radim Vansa
  - email: spederse@redhat.com
    name: St√•le W. Pedersen
  - email: wreicher@redhat.com
    name: Will Reichert
  maturity: alpha
  minKubeVersion: 1.16.0
  provider:
    name: Red Hat, Inc.
    url: https://horreum.hyperfoil.io
  replaces: horreum-operator.v0.0.2
  version: 0.0.0
